### ISSUE TITLE
Add dry_run and optional overwrite to sampling workflow

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#231]
For the sampling workflow, it would be nice to have an opportunity to do a "dry run" where we just initialize all the directories w/o actually running the model. 

It would additionally be nice to have an "overwrite" option, where, before we run a model, we identify if a model has successfully been run in this location. If we have an overwrite flag set to false, we will pass over running this model.

**Comment by cwschilly** [comment]
@eparish1 I've implemented the first part of the issue (`dry_run`) in PR #232. However, I have a question regarding the `overwrite` flag:

> before we run a model, we identify if a model has successfully been run in this location

What is a good indicator that the model has run successfully?

For example, in `test_sampling.py`, we define the model so that it writes a `passed.txt` file in every run directory. But obviously I can't look for that in the `run_sampling` function, since it's defined by the "user" (the test, in this case).

@fnrizzi fyi

**Comment by eparish1** [comment]
@cwschilly  

Great! I had a quick look and have one request. If we are doing a dry run, could we also hit the populate_run_directory? So basically the dry run would do everything but run the model.


Good question on how we know if the model has run. My thought was to have the sampling algorithm write something like "passed.txt", if the model runs successfully. So we could change this function in sampling.py:

```
def run_sample(run_directory: str, model: Model,
               parameter_sample: dict):
    '''
    Execute individual sample
    '''

    ts = time.time()
    flag = model.run_model(run_directory, parameter_sample)
    tf = time.time()
    run_time = tf - ts

    if flag == 0:
        print(f"Sample complete, run time = {run_time}")
        np.savetxt('passed.txt')
    else:
        print(f"Sample failed, run time = {run_time}")
    print(" ")
    return run_time
```
